#######################################
# Environment Configuration
#  - feel free to edit -
# -> for most changes you only have to
#         docker-compose up -d
#    to apply them
#######################################

#######################################
# Webserver

# General
WEB_DOCUMENT_ROOT=/app/
WEB_DOCUMENT_INDEX=index.php
CLI_SCRIPT=php /app/web/typo3/cli_dispatch.phpsh

#######################################
# SSH settings
# SSH public key (without comment):
# -> ssh-rsa AAAAB3Nza....
#  Github public ssh keys:
# -> https://github.com/USERNAME.keys
SSH_AUTH_KEY="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+S2LMdPu2VRCNMHdcrdtf6sR+4etcqp97vbqGFXIEyUCcAgL+usC9n50brRPvBHJj8Pl4SrpALnW07Yv5CojtD8KsKAoCYHuPdpMfiUdncmwOy7Z262zMJMVbFDWslQX+uxrFiU4Ko3cGwe7fqOn9u5VnoayOFlXrTHZCPgtmcGpHPNQUbdcyVbBkIu0MPgusRqk0jtZNUIAyP/e+cFt4uLO8JDhOssu7M+1fQlMzSzilH20il7T/WF/4hw7TKAsunheNMjnFUv4lj6mILxcPvZFVgPwcOBfkirxOSLnChKO8TC2/1Sp40ozlQLogj+ejBwznGjKwzVSnp2GirbsF
              ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDKddJQFU7KR206b77wSJUt5Nsl70/1fclZ5kyAvRig6Me5icY5qPKdgoFySkL9nnIg86rI4PVJi6vwCm+YhaMRdL3b56L2LsD4WfaBQMqgECPJwaQ0SGitRwTwO8NeKm8xD5nyMVdLlocihBmWuxjJAJ8PWChjpoVxhNUoditOREuAvdQ/zkhMNylglRXJfScded01f2sOxumryr/Nh/Xe3oue5c7qv4orbFi2DwPxG7x6rcZpHjWPgZFc2HYk7aHp/E2tB0WLBdBGQPY/9OduviMoO+3qr1E2iQWQhkHKHm85byhSt0cYLYN8fp9G0/kAD02+B9piCfZuC+4Ex0ryW9egVYOxPEloyQKi6sfrj96KGhsgU+0NM2WPXG4t9FhekHYwG11khxfpKbWBqpWNIBdJXQTwkn8ziBiymjPX9OhgDtR23zXhvqTKiaKkQF2Cx8kviVbVufnGRWeYNV7FKC1CS4cZSyJOgtojXX+JU41FYXOVM+MLguQRVGgojELEAZfnt3JQaOPonDvWRZtDmBfLIjf1bKqBLcsXCruALTCeHV+vvDLKPsGYTBWNsSm7s39xd519/zYPhjG0x/Xh8ljm6cw3ibbWvl+FOHI/N7PE4yvpodRfOFSY8T3WH7UXyiEjJPi7WhHiPYOUnZkttEUBGvjyrEjQ/hRUH9ktXw==
              ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC2+lN7+UF336M1yV5z1rxs+1AU8U9ooBOPh/kWIRtUujEeyw27z6ruNecdbYzL4BsGRHaG4RAif0/OKTf0NmZlOHR4FGOVjlVoERrKHjncCE4EJGMhW83lCaquJFnu5n0JLCFDLoquCBDmHSHx+ak6Oimi+4jok7PvWgGbe4D46zeS1MIV7h1g7C9R/9p8Kw7zO3h75m8RkSUWHNGWHNrjufje6gufx72cZoJ9Vb8h6/z35fUCV0Lg99CNFBTPmuqMj3r6HRvRm/kzIL1YJcAQC/7Y06GW1bFPoyw2cgIuczBtKNecZZINd8iOftTcM87kXKLRQtyaEZyS6RQuce1/"

#######################################
# MySQL settings
# -> if you change these settings
#    you have to remove the database:
#         docker-compose rm mysql
#    because it's stored database in
#    volume and provisioning is only
#    done once.
MYSQL_ROOT_PASSWORD=dev
MYSQL_USER=dev
MYSQL_PASSWORD=dev

#######################################
# PostgreSQL settings
POSTGRES_USER=dev
POSTGRES_PASSWORD=dev

#######################################
# FTP settings
FTP_USER=dev
FTP_PASSWORD=dev
FTP_PATH=/storage/ftp/
#FTP_PATH=/app/
