#######################################
# PHP application Docker container
#######################################
app:
  build: ${BOLERPLATEROOT}
  dockerfile: Dockerfile.development
  links:
    - mysql
    #- postgres
    #- mail
    #- elasticsearch
    #- redis
    #- ftp
  ports:
    - "8001:80"
    - "8443:443"
    - "10022:22"
  volumes:
    - ${PROJECTROOT}/:/app/
    - /tmp/debug/:/tmp/debug/
    - ${BOLERPLATEROOT}/:/docker/
  # cap and privileged needed for slowlog
  cap_add:
    - SYS_PTRACE
  privileged: true
  env_file:
    - ${BOLERPLATEROOT}/etc/environment.yml
    - ${BOLERPLATEROOT}/etc/environment.development.yml

#######################################
# MySQL server
#######################################
mysql:
  build: ${BOLERPLATEROOT}/docker/mysql
  dockerfile: MySQL-5.5
  #dockerfile: MySQL-5.6
  #dockerfile: MySQL-5.7
  #dockerfile: MariaDB-5.5
  #dockerfile: MariaDB-10
  #dockerfile: Percona-5.5
  #dockerfile: Percona-5.6
  ports:
    - 13306:3306
  volumes:
    - /tmp/debug/:/tmp/debug/
  env_file:
    - ${BOLERPLATEROOT}/etc/environment.yml
    - ${BOLERPLATEROOT}/etc/environment.development.yml

#######################################
# PostgreSQL server
#######################################
#postgres:
#  build: ${BOLERPLATEROOT}/docker/postgres/
#  ports:
#    - 15432:5432
#  env_file:
#    - ${BOLERPLATEROOT}/etc/environment.yml
#    - ${BOLERPLATEROOT}/etc/environment.development.yml

#######################################
# Elasticsearch
#######################################
#elasticsearch:
#  build: docker/elasticsearch/
#  ports:
#    - 19200:9200
#    - 19300:9300
#  volumes_from:
#    - storage
#  env_file:
#    - ${BOLERPLATEROOT}/etc/environment.yml
#    - ${BOLERPLATEROOT}/etc/environment.development.yml

#######################################
# Redis
#######################################
#redis:
#  build: ${BOLERPLATEROOT}/docker/redis/
#  env_file:
#    - ${BOLERPLATEROOT}/etc/environment.yml
#    - ${BOLERPLATEROOT}/etc/environment.development.yml

#######################################
# Memcached
#######################################
#memcached:
#  build: ${BOLERPLATEROOT}/docker/memcached/
#  env_file:
#    - ${BOLERPLATEROOT}/etc/environment.yml
#    - ${BOLERPLATEROOT}/etc/environment.development.yml

#######################################
# Mailcatcher
#######################################
#mail:
#  build: ${BOLERPLATEROOT}/docker/mail/
#  ports:
#    - 1080:1080
#  env_file:
#    - ${BOLERPLATEROOT}/etc/environment.yml
#    - ${BOLERPLATEROOT}/etc/environment.development.yml

#######################################
# FTP (vsftpd)
#######################################
#ftp:
#  build: ${BOLERPLATEROOT}/docker/vsftpd/
#  volumes_from:
#    - storage
#  volumes:
#    - ${PROJECTROOT}/:/application/
#  env_file:
#    - ${BOLERPLATEROOT}/etc/environment.yml
#    - ${BOLERPLATEROOT}/etc/environment.development.yml